name: DevCard
# https://github.com/dailydotdev/action-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: devcard
          commit_filename: devcard.png
          commit_message: "update ${filename}"