name: Most used (with details)
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, Procfile
          plugin_languages_skipped: lowlighter/metrics
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          commits_authoring: firstname lastname, username, SirHarveyBix@users.noreply.github.com
